### PR TITLE
Add dotenv to package.json

### PR DESCRIPTION
**Pull request by DevAmiyo**
**Please describe the changes this PR makes and why it should be merged:**
Added dotenv in package.json which was causing the error `Cannot find module 'dotenv'`
5c96f16 [`#902`](https://github.com/SudhanPlayz/Discord-MusicBot/pull/902)

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

**Comment by DarrenOfficial** [comment]
smhsmh bad commit

**Comment by JotaroKujo0525** [comment]
dotenv is already there right?

**Comment by JotaroKujo0525** [comment]
oh my goodness why didn't I notice
